spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.hsq           # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/cloud8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: hsq123                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: microcloud-config-dept-client-8001
  profiles: dev
    
      
security:
  user:
    name: hsq
    password: hello
    role:
    - USER
  basic:
    enabled: true
    
    
eureka:
  client:
    service-url:
      defaultZone: http://hsq:hello@eureka-7001.com:7001/eureka
      
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
    
info:
  app.name: hsq-microcloud
  company.name: www.hsq.com
  build.artifactId: $project.artifactId$
  build.version: $project.verson$
   
---    


server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.hsq           # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/cloud8001           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: hsq123                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: microcloud-config-dept-client-8001
  profiles: beta
    
      
security:
  user:
    name: hsq
    password: hello
    role:
    - USER
  basic:
    enabled: true
    
    
eureka:
  client:
    service-url:
      defaultZone: http://hsq:hello@eureka-7001.com:7001/eureka
      
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
    
info:
  app.name: hsq-microcloud
  company.name: www.hsq.com
  build.artifactId: $project.artifactId$
  build.version: $project.verson$
   
  